### ISSUE TITLE
slf4j.LoggersNamedForEnclosingClass should not throw NoSuchMethodError

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-logging-frameworks#102]
```
All sources parsed, running active recipes: org.jabref.config.rewrite.cleanup, org.openrewrite.java.logging.slf4j.LoggersNamedForEnclosingClass, org.openrewrite.java.logging.slf4j.ParameterizedLogging, org.openrewrite.java.logging.slf4j.Slf4jLogShouldBeConstant
The recipe produced an error. Please report this to the recipe author.

> Task :rewriteRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rewriteRun'.
> java.lang.RuntimeException: java.lang.NoSuchMethodError: 'void org.openrewrite.java.search.UsesType.<init>(java.lang.String)'
```

I only enabled `org.openrewrite.java.cleanup.StringLiteralEquality` as other recipe

This also refs https://stackoverflow.com/q/75941515/873282

**Comment by timtebeek** [comment]
Hmm; what version did run with? Because we [recently updated all usages of that `UsesType`](https://github.com/search?q=repo%3Aopenrewrite%2Frewrite-logging-frameworks%20UsesType&type=code) to use the two parameter version.

**Comment by koppor** [comment]
id("org.openrewrite.rewrite") version("5.40.4")

**Comment by koppor** [comment]
Are we two major versions behind? - https://github.com/openrewrite/rewrite/releases

Oh, the gradle plugin is versioned differently than the main code? https://github.com/openrewrite/rewrite-gradle-plugin/releases/tag/v5.40.4

**Comment by timtebeek** [comment]
Yes we version the plugins, the core of OpenRewrite and individual modules such as rewrite-logging-frameworks separately. We also offer [rewrite-recipe-bom](https://github.com/openrewrite/rewrite-recipe-bom) such that you have to be less explicit about lining up compatible versions.

Which version of the rewrite-logging-framework are you using?

**Comment by timtebeek** [comment]
I hope you'll agree with me closing this issue, as the bug refers to an older version of the recipe, whereas the latest version (and release) no longer has this issue; We're separately tracking what version of rewrite modules is used when in https://github.com/openrewrite/rewrite-gradle-plugin/issues/199, such that it's more obvious when any such issues occur.

Feel free to report back here if it's not resolved to your satisfaction!
